### ISSUE TITLE
Endpoint not considered

### ISSUE THREAD

**Issue by emaborsa** [janhommes/o.js#78] opened 2018-10-12 13:20 UTC
I have a web page where have to call different services, so in the beginning I configure _o_ followings:
`o().config({
    autoFormat: false,
    version: 3,
})`

The following _GET_ works:
`o(myUr/myEntity).get()`

The following _POST_ also works:
``o(myUrl/myEntity)``
``.post(data)``
``.save(onSuccess, onError)``

The following _PUT_/_PATCH_ does not work:
``o(myUrl/myEntity(theEntityId))``
``.patch(data)``
``.save(onSuccess, onError)``

I get a 404 with the wrong url. It takes the _window.location.position_ instead the `myUrl + '/myEntity(theEntityId)'`

I debugged the o.js library v0.4.0, the problem seems to be on line 957: `var endpoint = base.oConfig.endpoint + (endsWith(base.oConfig.endpoint, '/') ? '' : '/') + '$batch';` where `base.oConfig.endpoint` is null.

In the other scenario, configuring at the beginning as follows, it works fine:
`o().config({
    endpoint: 'myUrl',
    autoFormat: false,
    version: 3,
})`

On line 120: `function oData(res, config) {` the passed res variable seems not be used.

Edit:

Sorry, I forgot that I use the batch as follows:
``o(myUrl/myEntity(theEntityId))``
``.patch(data)``
``.batch(myUrl/myEntity(anotherEntityId))``
``.patch(anotherData)``
``.save(onSuccess, onError)``

**Comment by janhommes** [comment] 2018-10-12 14:11
That is an issue. I guess it is on the lines `500-506`. We try to be too smart here. Can you try to remove that line and see if it is working?

**Comment by janhommes** [comment] 2018-10-15 07:52
yes.

So the issue is that it never should get to `957` because that is only for BATCH request, which means which should only happen if you do multiple put or post without saving. So somehow you have more then one request pending.

Can you run the put in isolation without any other get/post/something? Does it work then?

**Comment by emaborsa** [comment] 2018-10-22 09:57
Sorry, little mistake. I forgot to say that I use the `batch`. I updated the question.

**Comment by emaborsa** [comment] 2018-10-22 12:46
Another unclear point, on line 1010 the variable `routeName` variable set to res. routeName does not exist in the entire script...

**Comment by janhommes** [comment] 2018-10-22 20:44
yes, the `routeName` can be removed, that's right.

I guess there is nothing we can do about the endpoint. All Batch requests are sent to one endpoint, therefore it is not possible to define multiple URLs and that is why we just take into account the `oConfig.endpoint`. Which url would you suggest to use, the first one?

**Comment by emaborsa** [comment] 2018-10-23 06:03
Well, I think the library should use the oConfig.endpoint as standard. IF I pass another url, it should be taken but not override the `base` one.
Otherwise IMHO there should be a null check on the endpoint and throw an error when it is.

**Comment by janhommes** [comment] 2019-02-05 18:17
should be fixed by: #83

**Closed by janhommes** 2019-02-05 18:17 UTC
Labels: bug
